export const pokemonTypes = [
    { name: "bug", color: "#7bcf00" },
    { name: "dark", color: "#5a566a" },
    { name: "dragon", color: "#0076ff" },
    { name: "electric", color: "#f4c430" },
    { name: "fairy", color: "#ff76ff" },
    { name: "fighting", color: "#ff215b" },
    { name: "fire", color: "#FFA860" },
    { name: "flying", color: "#89bdff" },
    { name: "ghost", color: "#4e6aff" },
    { name: "grass", color: "#81BD8C" },
    { name: "ground", color: "#ff6b0d" },
    { name: "ice", color: "#2ee4c6" },
    { name: "normal", color: "#9fa39d" },
    { name: "poison", color: "#7744AA" },
    { name: "psychic", color: "#ff6c64" },
    { name: "rock", color: "#d8bc5a" },
    { name: "steel", color: "#23a1bd" },
    { name: "water", color: "#37A7F2" },
  ];